apiVersion: apps/v1
kind: Deployment
metadata:
  name: parkingservice
  labels:
    app: parkingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parkingservice
  template:
    metadata:
      labels:
        app: parkingservice
    spec:
      containers:
        - name: parkingservice
          image: ghcr.io/agile-software-engineering-25/team-3-backend-parking-lot-analysis:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /parkingservice/actuator/health # falls Actuator nicht aktiv: anpassen!
              port: 8080
            initialDelaySeconds: 30 # mehr Zeit vor dem ersten Check
            periodSeconds: 10 # Check alle 10s
            failureThreshold: 6 # bis zu 1 Minute unready erlaubt
          livenessProbe:
            httpGet:
              path: /parkingservice/actuator/health # falls Actuator nicht aktiv: anpassen!
              port: 8080
            initialDelaySeconds: 180 # Pod darf bis zu 3 Minuten brauchen zum Start
            periodSeconds: 20 # Check alle 20s
            failureThreshold: 6 # bis zu 2 Minuten Fehler erlaubt
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
