apiVersion: apps/v1
kind: Deployment
metadata:
  name: parkingservice
  labels:
    app: parkingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parkingservice
  template:
    metadata:
      labels:
        app: parkingservice
    spec:
      containers:
        - name: parkingservice
          image: ghcr.io/agile-software-engineering-25/team-3-backend-parking-lot-analysis
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /parkingservice # you might need to change this to a health endpoint of your application
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /parkingservice # you might need to change this to a health endpoint of your application
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          env: # add environment variables here if needed
            - name: SOME_ENVIRONMENT_VARIABLE
              value: "ᓚᘏᗢ"
